version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: ./files/postgres.Dockerfile
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:${GUEST_PG_PATH}
    environment:
      - PGDATA=${GUEST_PGDATA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
volumes:
   pgdata:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: ${HOST_PG_PATH}
